remote_theme: pages-themes/modernist@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one

title: Reversing Blog
description: Using x64dbg, IDA Pro & other software to analyze and patch software
